FEWEB02 - Siswa - pembuatan halaman home
iqbalfarhan/absensimagang pull request #10
Opened 2024-03-14 09:41 UTC by rigel-sayudha

2024-03-18 08:11 UTC, iqbalfarhan requested changes

2024-03-18 08:11 UTC, iqbalfarhan commented on resources/views/livewire/widget/watch.blade.php
> +            x-init="setInterval(() => {
coba pakai wire poll aja. ini formatnya tidak sesuai seharusnya tidak ada AM/PMnya

2024-03-18 08:12 UTC, iqbalfarhan commented
ini labelnya aku balikin ke draft dulu. tolong diperbaiki

2024-03-18 12:16 UTC, rigel-sayudha commented on resources/views/livewire/widget/watch.blade.php
> +            x-init="setInterval(() => {
sudah fix mas

2024-03-19 00:10 UTC, iqbalfarhan approved these changes
fetch dari main dulu kemudian commit ulang

2024-03-19 00:11 UTC, merged